name: obs-planning

services:
  backend:
    build: backend
    ports:
      - 8080:80
    environment:
      OBS_DB_HOST: database
      OBS_DB_USER: obs-user
      OBS_DB_PORT: 5432
      OBS_DB_NAME: obs-db
      OBS_DB_PASSWORD: $OBS_DB_PASSWORD
    networks:
      - obs
  astrobackend:
    build: astrobackend
    ports:
      - 8081:8000
    networks:
      - obs
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $OBS_DB_PASSWORD
      POSTGRES_USER: obs-user
      POSTGRES_DB: obs-db
    networks:
      - obs
networks:
  obs:
    driver: bridge

